version: "3.7"

services:
  varnish:
    build: ./varnish
    ports:
      - "8080:80"
    networks:
      - varnish_network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "500M"  # 500 MB
        reservations:
          cpus: "0.5"
          memory: "500M"
    command: 
       -s default=malloc,1G
       -s slot1=malloc,1G
       -s slot2=malloc,1G
  
  backend:
    build: ./caching-supported-backend
    ports:
      - "8083:8083"
    networks:
      - varnish_network
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "1G"  # 1 GB
        reservations:
          cpus: "2.0"
          memory: "1G"

  backend-second:
    build: ./simple-backend
    ports:
      - "8084:8084"
    networks:
      - varnish_network
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "1G"  # 1 GB
        reservations:
          cpus: "2.0"
          memory: "1G"
  

networks:
  varnish_network:
    external: true
    