version: "3.7"

services:
  varnish:
    build: ./varnish
    ports:
      - "8080:80"
    networks:
      - varnish_network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "500M"  # 500 MB
        reservations:
          cpus: "0.5"
          memory: "500M"
    environment:
      ORG1_CACHE_MAX_SIZE: "3221225472"  # 3GB
      ORG2_CACHE_MAX_SIZE: "1073741824"  # 1GB
      DEFAULT_CACHE_MAX_SIZE: "1048576"   # 1MB
    command: 
       -s default=malloc,1G
       -s org1=malloc,3G
       -s org2=malloc,1G
  
  backend:
    build: ./backend
    ports:
      - "8083:8083"
    networks:
      - varnish_network
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "1G"  # 1 GB
        reservations:
          cpus: "2.0"
          memory: "1G"
  

networks:
  varnish_network:
    external: true
    